/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.app;

import java.awt.Color;
import java.awt.Dimension;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JFileChooser;

/**
 *
 * @author Sail3
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private final Lienzo lienzo = new Lienzo();
    private final JComponent elementoMuestra = lienzo.getMedidaElemento();
    public VentanaPrincipal() {
        initComponents();
        getContentPane().add(lienzo,java.awt.BorderLayout.CENTER);
        establecerTamano();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VPBarraTareas = new javax.swing.JToolBar();
        jBtnLinea = new javax.swing.JButton();
        jBtnLibre = new javax.swing.JButton();
        jBarraTamano = new javax.swing.JSlider();
        jBtnColor = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        VPBarraMenu = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMIGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMICerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VPBarraTareas.setBackground(new java.awt.Color(255, 255, 255));
        VPBarraTareas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VPBarraTareas.setRollover(true);

        jBtnLinea.setBackground(new java.awt.Color(255, 255, 255));
        jBtnLinea.setText("Linea");
        jBtnLinea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        jBtnLinea.setFocusable(false);
        jBtnLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLineaActionPerformed(evt);
            }
        });
        VPBarraTareas.add(jBtnLinea);

        jBtnLibre.setBackground(new java.awt.Color(255, 255, 255));
        jBtnLibre.setText("Libre");
        jBtnLibre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        jBtnLibre.setFocusable(false);
        jBtnLibre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLibre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLibreActionPerformed(evt);
            }
        });
        VPBarraTareas.add(jBtnLibre);

        jBarraTamano.setBackground(new java.awt.Color(255, 255, 255));
        jBarraTamano.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jBarraTamanoStateChanged(evt);
            }
        });
        VPBarraTareas.add(jBarraTamano);
        VPBarraTareas.add(elementoMuestra);

        jBtnColor.setBackground(new java.awt.Color(255, 255, 255));
        jBtnColor.setForeground(lienzo.getColor());
        jBtnColor.setText("Color");
        jBtnColor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        jBtnColor.setFocusable(false);
        jBtnColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnColorActionPerformed(evt);
            }
        });
        VPBarraTareas.add(jBtnColor);

        jBtnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        jBtnLimpiar.setFocusable(false);
        jBtnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });
        VPBarraTareas.add(jBtnLimpiar);

        getContentPane().add(VPBarraTareas, java.awt.BorderLayout.NORTH);

        jMArchivo.setText("Archivo");

        jMIGuardar.setText("Guardar");
        jMIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGuardarActionPerformed(evt);
            }
        });
        jMArchivo.add(jMIGuardar);
        jMArchivo.add(jSeparator1);

        jMICerrar.setText("Cerrar");
        jMICerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICerrarActionPerformed(evt);
            }
        });
        jMArchivo.add(jMICerrar);

        VPBarraMenu.add(jMArchivo);

        jMenu2.setText("Ayuda");
        VPBarraMenu.add(jMenu2);

        setJMenuBar(VPBarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBarraTamanoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jBarraTamanoStateChanged
        establecerTamano();
    }//GEN-LAST:event_jBarraTamanoStateChanged

    private void jBtnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLineaActionPerformed
        lienzo.setFigura(Lienzo.LINEA);
        establecerTamano();
    }//GEN-LAST:event_jBtnLineaActionPerformed

    private void jBtnLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLibreActionPerformed
        lienzo.setFigura(Lienzo.CIRCULO);
        establecerTamano();
    }//GEN-LAST:event_jBtnLibreActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        lienzo.limpiar();
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jMICerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICerrarActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMICerrarActionPerformed

    private void jBtnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnColorActionPerformed
        Color color = JColorChooser.showDialog(this, "Seleccione Color", lienzo.getColor());
        lienzo.setColor(color);
        jBtnColor.setForeground(color);
    }//GEN-LAST:event_jBtnColorActionPerformed

    private void jMIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGuardarActionPerformed

        JFileChooser seleccionador = new JFileChooser();
        int resultado = seleccionador.showSaveDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            try {
                ImageIO.write(lienzo.getImagen(), "jpg", seleccionador.getSelectedFile());
            } catch (IOException ex) {
                System.out.println("error");
                ex.printStackTrace();
            }
            System.out.println(seleccionador.getSelectedFile());
        }
        
    }//GEN-LAST:event_jMIGuardarActionPerformed
    private void establecerTamano(){
        int tamano = 5 + jBarraTamano.getValue() / 10;
        switch (lienzo.getFigura()) {
            case Lienzo.CIRCULO:
                lienzo.setCirculo(new Dimension(tamano, tamano));
                break;
            case Lienzo.LINEA:
                lienzo.setLinea(new Dimension(tamano, tamano));
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar VPBarraMenu;
    private javax.swing.JToolBar VPBarraTareas;
    private javax.swing.JSlider jBarraTamano;
    private javax.swing.JButton jBtnColor;
    private javax.swing.JButton jBtnLibre;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnLinea;
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenuItem jMICerrar;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
